### ISSUE TITLE
Socket was readable but we read 0. This usually means that the connection is half closed this mark it as broken

### ISSUE THREAD

**Issue by Ajatars** [rusty-celery/rusty-celery#360]
When my worker runs a task for a period of time, the following bug will appear:
```
2023-04-18T03:03:43.454931Z ERROR lapin::io_loop: Socket was readable but we read 0. This usually means that the connection is half closed this mark it as broken
2023-04-18T03:03:43.454965Z ERROR lapin::io_loop: error doing IO error=IOError(Kind(ConnectionAborted))
2023-04-18T03:03:43.455010Z ERROR lapin::channels: Connection error error=IO error: connection aborted
2023-04-18T03:03:43.455174Z ERROR celery::app: AMQP error "IO error: connection aborted"
```
I don't know if it's related to the code for creating the app below (I just want to create a global 'cellery_app'):
```
init.rs:
pub async fn init_celery_app(mq_address: String) -> Arc<Celery> {
    let celery_app = celery::app!(
    broker = AMQPBroker { &mq_address },
    tasks = [
        some_task
    ],
    task_routes = [
    "*" => "celery",
    ],
    prefetch_count = 2,
    heartbeat = Some(10),
    )
    .await.unwrap();
    celery_app
}

main.rs:
use tokio::sync::OnceCell;

pub static CELERY_APP: OnceCell<Arc<Celery>> = OnceCell::const_new();

#[tokio::main]
async fn main() -> std::io::Result<()> {
       ......
      CELERY_APP
        .get_or_init(|| async move { init_celery_app(mq_address).await })
        .await;
      ......
}

worker.rs:
......
let celery_app = CELERY_APP.get().unwrap().clone();
celery_app
                .send_task(some_task::new(task.task_id, args))
                .await?;
......
```

**System (please complete the following information):**
 - OS: [mac]
 - Broker [AMQP]
 - Version [docker rabbitmq:latest]

**Comment by Keruspe** [comment]
What amqp server is used? Is there any specific heartbeat configuration? Is it being a NAT?

**Comment by Keruspe** [comment]
Also, could be interesting to see the server logs around that time

**Comment by Ajatars** [comment]
I am using the rabbitmq deployed by Docker and found that my heartbeat has timed out. The Woker I am running is probably the following code, and I don't understand why my heartbeat has timed out?
woker:
```
#[celery::task]
pub async fn test_task() -> TaskResult<bool> {
......
let handler = thread::spawn(move || {
//Tasks that require a certain amount of time to run, may exceed 60 seconds
})
handler.join().unwrap();
......
Ok(true)
}
```

log:
```
[error] <0.25347.0> closing AMQP connection <0.25347.0> (172.20.0.1:58486 -> 172.20.0.2:5672):
[error] <0.25347.0> missed heartbeats from client, timeout: 60s
```

**Comment by Keruspe** [comment]
Can you retry with RUST_LOG=debug?

**Comment by Ajatars** [comment]
```
2023-04-23T18:48:11.012434Z DEBUG lapin::channels: send heartbeat
2023-04-23T18:48:11.012501Z ERROR lapin::io_loop: error doing IO error=IOError(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })
2023-04-23T18:48:11.012576Z ERROR lapin::channels: Connection error error=IO error: Connection reset by peer (os error 54)
2023-04-23T18:48:11.012619Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
2023-04-23T18:48:11.012687Z DEBUG Connection{peer=Client}: h2::proto::connection: Connection::poll; connection error error=GoAway(b"", NO_ERROR, Library)
2023-04-23T18:48:11.012729Z ERROR celery::app: AMQP error "IO error: Connection reset by peer (os error 54)"    
thread 'main
' panicked at :' BrokerError(AMQPError(IOError(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })))', src/bin/worker.rs:18:10
```

```
 0: rust_begin_unwind
             at /rustc/17c11672167827b0dd92c88ef69f24346d1286dd/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/17c11672167827b0dd92c88ef69f24346d1286dd/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/17c11672167827b0dd92c88ef69f24346d1286dd/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::expect
             at /rustc/17c11672167827b0dd92c88ef69f24346d1286dd/library/core/src/result.rs:1049:23
   4: worker::main::{{closure}}
             at ./src/bin/worker.rs:15:5
   5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/lq/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.27.0/src/runtime/park.rs:283:63
   6: tokio::runtime::coop::with_budget
             at /Users/lq/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.27.0/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at /Users/lq/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.27.0/src/runtime/coop.rs:73:5
   8: tokio::runtime::park::CachedParkThread::block_on
             at /Users/lq/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.27.0/src/runtime/park.rs:283:31
   9: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/lq/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.27.0/src/runtime/context.rs:315:13
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/lq/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.27.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  11: tokio::runtime::runtime::Runtime::block_on
             at /Users/lq/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.27.0/src/runtime/runtime.rs:304:45
  12: worker::main
             at ./src/bin/worker.rs:15:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/17c11672167827b0dd92c88ef69f24346d1286dd/library/core/src/ops/function.rs:250:5
```

**Comment by Ajatars** [comment]
I replaced all threads:: spawn with tokio:: spawn to solve the problem of 'send heartbeat' being blocked, allowing workers to send heartbeats while executing tasks
